"""idempotency

Revision ID: 1c243cbf1b6f
Revises: 14042496e1f6
Create Date: 2025-06-10 10:28:57.889984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c243cbf1b6f"
down_revision: Union[str, None] = "14042496e1f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
    )
    op.create_unique_constraint(None, "bookings", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="unique")
    op.drop_column("bookings", "idempotency_key")
    # ### end Alembic commands ###
