"""idempontency-key

Revision ID: 14042496e1f6
Revises: 433150ce3719
Create Date: 2025-06-10 09:41:19.598175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14042496e1f6"
down_revision: Union[str, None] = "433150ce3719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balance_transactions",
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
    )
    op.create_unique_constraint(
        None, "balance_transactions", ["idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "balance_transactions", type_="unique")
    op.drop_column("balance_transactions", "idempotency_key")
    # ### end Alembic commands ###
